@include('user.page-layout.header')
@yield('css')

@yield('product_detail')
@yield('cart')
@yield('address')
@yield('payment_method')
@yield('login')
@yield('regiser')
@yield('reset_password')
@yield('account_profile')
@yield('account_orders')
@yield('account_dashboard')
@yield('account_saved_address')
@yield('account_edit_profile')
@yield('shop_grid_type_5')
@yield('shop_grid')
@yield('wishlist')
@yield('billing_details')


@include('user.page-layout.footer')